### ISSUE TITLE
本地上传200M的大文件出现错误

### ISSUE THREAD

**Issue by a270443177** [imu-hupeng/cos-python3-sdk#1]
Traceback (most recent call last):
  File "C:/Users/xxx/PycharmProjects/cos.py", line 7, in <module>
    status = bucket.upload_file(real_file_path="d:\\592a82cb3c988.zip",file_name="592a82cb3c988.zip",  dir_name=None)
  File "C:\Python34\lib\site-packages\cos_lib3\cos.py", line 137, in upload_file
    return str(eval(r.content.decode('utf8')).get('data'))
  File "<string>", line 1
    <html>
    ^
SyntaxError: invalid syntax

**Comment by imu-hupeng** [comment]
预计本周末能解决bug

**Comment by a270443177** [comment]
我写粗略的写了一个分片上传的，希望你能更新一下，最好事能和简单上传合并，通过判断文件大小来处理是简单上传还是分片上传，下面是我分离出来的代码，有点邋遢

    def _upload_slice_control(self, file_size, slice_size):
        headers = {}
        headers['Authorization'] = CosAuth(self.config).sign_more(self.config.bucket, '', 30)
        data = {'op': 'upload_slice_init', 'filesize': str(file_size), 'slice_size': str(slice_size), 'biz_attr': '','insertOnly': '0'}
        r = requests.post(url=self.url, files=data, headers=headers)
        return str(eval(r.content.decode('utf8')).get('data').get('session'))

    def _upload_slice_data(self,filecontent,session,offset):
        headers = {}
        headers['Authorization'] = CosAuth(self.config).sign_more(self.config.bucket, '', 30)
        data = {'op': 'upload_slice_data', 'filecontent': filecontent, 'session': session, 'offset': str(offset)}
        r = requests.post(url=self.url, files=data, headers=headers)
        return str(eval(r.content.decode('utf8')).get('data'))

    def _upload_slice_finish(self,session, file_size):
        headers = {}
        headers['Authorization'] = CosAuth(self.config).sign_more(self.config.bucket, '', 30)
        data = {'op': 'upload_slice_finish', 'session': session, 'filesize': str(file_size)}
        r = requests.post(url=self.url, files=data, headers=headers)
        return str(eval(r.content.decode('utf8')).get('data'))

    def upload_slice_file(self, real_file_path, slice_size,file_name, offset=0, dir_name=None):
        if dir_name is not None and dir_name[0] == '/':
            dir_name = dir_name[1:len(dir_name)]
        if dir_name is None:
            dir_name = ""
        self.url = 'http://' + self.config.region + '.file.myqcloud.com/files/v2/' + str(self.config.app_id) + '/' + self.config.bucket
        if dir_name is not None:
            self.url = self.url + '/' + dir_name
        self.url = self.url + '/' + file_name
        file_size = os.path.getsize(real_file_path)
        session = self._upload_slice_control(file_size=file_size, slice_size=slice_size)
        with open(real_file_path,'rb') as local_file:
            while offset < file_size:
                file_content = local_file.read(slice_size)
                self._upload_slice_data(filecontent=file_content, session=session, offset=offset)
                offset += slice_size
            r = self._upload_slice_finish(session=session, file_size=file_size)
        return r

**Comment by imu-hupeng** [comment]
thank you

**Comment by imu-hupeng** [comment]
代码已经合并到主分支,且已经推送至PyPi,感谢您的支持

**Comment by 643435675** [comment]
使用demo中调用方法，其中region='ap-shanghai'

结果：
ssss b"You do not have permission to get URL '/files/v2/1255701127/matrix-dev-1255701127%20/JANESI/777.jpg' from this server."
************************************************************

**Comment by imu-hupeng** [comment]
你好：     由于最近忙于实习项目，无法立即排查错误，对此我深感抱歉，如果我的库无法使用，建议您尝试一下其他库，例如 https://github.com/a270443177/cos-python3-sdk-v4 。
    感谢您的反馈。

------------------
Cordial greetings · 诚挚问候
胡鹏(Hu Peng) @ IMUDGES 2015
-Inner Mongolia University Developer Group of Elite Student, 内蒙古大学精英学生开发者联盟


You can contact me by these ways:
你能够通过以下方式与我联系：

 移动电话 Cell Phone: +86 18847163389

QQ：545061225

微信 WeChat：wxid_hupeng

主页 Personal page:http://www.hupeng.me/

coding： https://coding.net/u/imu-hupeng

gitHub: https://github.com/imu-hupeng



 

 
 
 
------------------ Original ------------------
